#!/usr/bin/env bash
# Package this pipeline as a standalone repo somebody else can clone and use.
#
#   bash share.sh ~/Desktop/notebook-kit
#
# Copies the engine, the build script, the docs and the template book. Leaves
# behind the written books, the lecture transcripts and every generated PDF,
# because those are yours and they are what makes the directory large.
#
# The result is a git repository with one commit. Push it anywhere, or zip it.
set -e
cd "$(dirname "$0")"

DEST="${1:-}"
[ -z "$DEST" ] && { echo "usage: bash share.sh <destination-directory>"; exit 1; }
[ -e "$DEST" ] && { echo "share.sh: $DEST already exists. Pick a new path."; exit 1; }

mkdir -p "$DEST/engine" "$DEST/books/figures" "$DEST/sources"

cp engine/build.py engine/pdf.py engine/lint.py engine/questions.py \
   engine/sketch.py engine/transcript.py engine/theme.css "$DEST/engine/"
cp -R engine/fonts "$DEST/engine/fonts"
cp books/example.md "$DEST/books/"
cp books/figures/example.py "$DEST/books/figures/"
cp README.md GETTING-STARTED.md AUTHORING.md share.sh "$DEST/"

# The registry with the personal books removed, and the README's table of
# those books replaced by what the packaged copy actually contains.
# Shipping a contents page for files that are not there is worse than
# shipping no table at all.
python3 - "$DEST" <<'PY'
import re, sys, pathlib
dest = pathlib.Path(sys.argv[1])
s = pathlib.Path("build.sh").read_text()
s = re.sub(r"BOOKS=\(\n(?:.*\n)*?\)",
           'BOOKS=(\n'
           '  # add one line per book. nothing else needs to know about it.\n'
           ')', s, count=1)
(dest / "build.sh").write_text(s)

r = pathlib.Path("README.md").read_text()
r = re.sub(r"\| # \| Book \| Source \| Built from \|\n(?:\|.*\|\n)+",
           "| # | Book | Source | What it is |\n"
           "|---|---|---|---|\n"
           "| XX | Example Book | `books/example.md` | The template. "
           "Every directive and mark, rendered |\n"
           "| 00 | Question Bank | `books/question-bank.md` | Generated "
           "once you have books to collect from |\n", r, count=1)
r = r.replace("bash build.sh object-storage         # one book, Reading edition\n"
              "bash build.sh object-storage tablet  # one book, one named edition",
              "bash build.sh example                # one book, Reading edition\n"
              "bash build.sh example tablet         # one book, one named edition")
r = r.replace(":::figure authz-layers", ":::figure request-path")
(dest / "README.md").write_text(r)
PY

# Keep this verbatim MIT. GitHub's licence detection is exact-match, and an
# appended note about the fonts makes the repo show as "Other". The font
# caveat lives in the README and in engine/fonts/NOTICE.md instead.
cat > "$DEST/LICENSE" <<LIC
MIT License

Copyright (c) $(date +%Y) Shahid Raza

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
LIC

cat > "$DEST/.gitignore" <<'GI'
__pycache__/
.DS_Store
html/
pdf/
GI

cat > "$DEST/books/README.md" <<'BR'
# books/

One markdown file per book, plus `figures/<book>.py` for any hand-drawn
figures. `example.md` is the template: copy it, then add a line to the `BOOKS`
array in `../build.sh`.

`question-bank.md` is generated by `engine/questions.py` on every build once you
have books to collect from. Never edit it; edit the book the prompt came from.
BR

cat > "$DEST/sources/README.md" <<'SR'
# sources/

Lecture transcripts, if you build books from video. Pull them with:

    python3 engine/transcript.py "<playlist or video url>" sources

One file per video, front matter plus timestamped paragraphs. These are raw
material, not notes, and are not meant to be read straight through.
SR

cd "$DEST"
git init -q
git add -A
# Use whatever git identity is configured here; fall back only if there is none,
# so the first commit is not authored by a placeholder.
if git config user.email >/dev/null 2>&1 || git config --global user.email >/dev/null 2>&1; then
  git commit -qm "Study notebook pipeline: markdown to annotatable PDF"
else
  git -c user.name="notebook-kit" -c user.email="noreply@localhost" \
      commit -qm "Study notebook pipeline: markdown to annotatable PDF"
fi

echo "Packaged into $DEST"
echo
echo "  cd $DEST && bash build.sh example"
echo
echo "Then push it wherever you like:"
echo "  gh repo create <name> --private --source=$DEST --push"
