#!/usr/bin/env python3
"""Collect every prompt in the notebooks into one question bank.

    python3 engine/questions.py books/question-bank.md \
        "01|Large-Scale Data Ingestion|books/large-scale-ingestion.md" ...

The notebooks already carry the questions: `:::ask` is an interviewer's
follow-up and its body is the answer, `:::recall` is a self-graded prompt,
`:::redraw` is a drawing plate. Scattered through five books they only fire
where you happen to be reading. Gathered here they can be worked cold, which
is the condition an interview actually tests.

Nothing is authored in this file. Edit the notebooks; this file follows.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build                                            # noqa: E402

COLLECT = ("ask", "recall", "redraw")
DEFAULT_PART = "Opening"

# A book's closing part is called "Appendices" because that is what it is
# inside something you read front to back. Pulled out of the book, those
# prompts are the end-of-book self-test, so the bank calls them what they are.
RENAME = {"Appendices": "Final review"}

# Ruled lines for a written answer, from how much there is to say. Too few and
# you compress; too many and the page invites padding.
CHARS_PER_LINE = 78
MIN_LINES, MAX_LINES = 4, 9


def blocks(lines, i):
    """Consume the directive opening at lines[i]; return (arg, body, next_i)."""
    arg = re.match(r"^:::(\w+)[ \t]*(.*)$", lines[i]).group(2)
    depth, body, i = 1, [], i + 1
    while i < len(lines):
        if re.match(r"^:::\w+", lines[i]):
            depth += 1
        elif lines[i].strip() == ":::":
            depth -= 1
            if depth == 0:
                break
        body.append(lines[i])
        i += 1
    return arg, "\n".join(body), i + 1


def scan(path):
    """Every prompt in one book, in reading order, tagged with where it sits."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().split("\n")

    found, part, sec, i = [], DEFAULT_PART, "", 0
    while i < len(lines):
        if re.match(r"^:::(\w+)", lines[i]):
            name = re.match(r"^:::(\w+)", lines[i]).group(1)
            arg, body, i = blocks(lines, i)
            if name == "part":
                _, _, title = arg.partition("|")
                part = title.strip()
            elif name in COLLECT:
                found.append({"kind": name, "arg": arg.strip(),
                              "body": body.strip(), "part": part, "sec": sec})
            continue
        h = re.match(r"^##\s+(.*)$", lines[i])
        if h:
            num, _ = build.split_number(h.group(1).strip())
            sec = num
        i += 1
    return found


def lines_for(text):
    n = round(len(text) / CHARS_PER_LINE)
    return max(MIN_LINES, min(MAX_LINES, n))


def clean(text):
    """One line, and no stray emphasis to leak out of a wrapper."""
    return " ".join(text.replace("*", "").split())


def emit(dst, specs):
    books = []
    for spec in specs:
        num, title, path = spec.split("|")
        books.append({"num": num, "title": title, "path": path,
                      "items": scan(path)})

    total = sum(len(b["items"]) for b in books)
    answered = sum(1 for b in books for it in b["items"] if it["kind"] == "ask")
    span = f"{books[0]['num']} to {books[-1]['num']}"

    out = [
        ":::title Work in pen. A prompt you can only half answer is the whole "
        "point of the exercise: mark it, and go back to the section it names.",
        "Study Notebook / 00",
        "Question Bank",
        f"{total} prompts pulled from notebooks {span}, answers at the back",
        "Generated from the notebooks. Do not edit this file.",
        ":::",
        "",
        "## How to use this book",
        "",
        "This is not a book to read. Every prompt in it already appears inside "
        "a notebook, next to the passage that answers it, which is exactly why "
        "answering it there proves very little. ==You do not have a knowledge "
        "problem. You have a recall-under-pressure problem==, and the only "
        "thing that fixes it is being asked cold.",
        "",
        "Each prompt carries the notebook and section it came from, printed "
        "small beside its number, so a blank is never a dead end.",
        "",
        f"Of the {total} prompts, {answered} came from an __Interviewer asks__ "
        f"block and have a written answer in the last part, under the same "
        f"number. The rest are self-graded: the section named beside the "
        f"prompt is the answer.",
        "",
        ":::do Work it in three passes",
        "- ((Cold)). Cover nothing, look nothing up, write what you have. A "
        "wrong answer written down is worth more than a right answer read.",
        "- ((Check)). Compare against the key or the section. Mark each prompt "
        "as solid, shaky or blank.",
        "- ((Again, later)). Come back to the shaky and blank ones only, a few "
        "days later. This is the pass that does the work.",
        ":::",
        "",
        ":::key",
        "Say the answer out loud before you write it. An interview is spoken, "
        "and !!an answer you can write but not say is not an answer you have!!.",
        ":::",
        "",
        ":::toc",
        ":::",
        "",
    ]

    qn, key, sec_no = 0, [], 0
    for book in books:
        if not book["items"]:
            continue
        n = len(book["items"])
        out += [f":::part {book['num']} | {book['title']}",
                f"{n} prompts from Notebook {book['num']}. "
                f"Source: `{os.path.basename(book['path'])}`.",
                ":::", ""]

        by_part = []
        for it in book["items"]:
            if not by_part or by_part[-1][0] != it["part"]:
                by_part.append((it["part"], []))
            by_part[-1][1].append(it)

        for part_title, items in by_part:
            sec_no += 1
            title = RENAME.get(part_title.strip(), part_title)
            out += [f"## {sec_no}. {clean(title)}", ""]
            for it in items:
                qn += 1
                tag = f"Q{qn}"
                ref = f"{book['num']} / {it['sec']}" if it["sec"] else book["num"]
                if it["kind"] == "redraw":
                    prompt, _, hint = it["arg"].partition("|")
                    # A plate has no ruled lines to hang the reference off, so
                    # it goes in the hint or the page has no way back.
                    where = (f"Notebook {book['num']}, section {it['sec']}."
                             if it["sec"] else f"Notebook {book['num']}.")
                    hint = " ".join(x for x in (hint.strip(), where) if x)
                    out += [f":::redraw {tag}. {prompt.strip()} | {hint}", ":::", ""]
                    continue
                if it["kind"] == "recall":
                    prompt, _, count = it["arg"].partition("|")
                    nlines = (int(count.strip()) if count.strip().isdigit()
                              else lines_for(prompt))
                    text = prompt.strip()
                else:
                    text = it["arg"]
                    nlines = lines_for(it["body"])
                    key.append((tag, book, it, text))
                out += [f":::quiz {tag} | {ref} | {nlines}", text, ":::", ""]

    out += [f":::part {int(books[-1]['num']) + 1:02d} | Answers",
            f"The {answered} interviewer questions, answered. Everything else "
            "is graded against the section beside the prompt.",
            ":::", ""]

    # One section per notebook rather than one long run: twenty-odd pages of
    # answers under a single contents line cannot be navigated.
    current = None
    for tag, book, it, text in key:
        if book["num"] != current:
            current = book["num"]
            sec_no += 1
            out += [f"## {sec_no}. Answers, Notebook {book['num']}", ""]
        ref = f"Notebook {book['num']}, section {it['sec']}" if it["sec"] \
            else f"Notebook {book['num']}"
        out += [f"**{tag}** {clean(text)}  *{ref}.*", "", it["body"], ""]

    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out).rstrip() + "\n")
    print(f"    {dst}  {total} prompts, {answered} with answers, "
          f"{sec_no} sections")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        raise SystemExit('usage: questions.py out.md "NN|Title|path" ...')
    emit(sys.argv[1], sys.argv[2:])
